__HOMEWORK 14__
<br>
Full Name: Nguyễn Thị Minh Ngọc
<br>
Student ID: 11219280
<br>
Class: DSEB 63

In [37]:
import numpy as np
import json

## Exercise 1

In [38]:
class Story:
    
    def __init__(self, story = None):
        if story == None:
            self.path = input("Enter the path of the story chosen: ")
        else:
            self.path = story
        # attributes
        self.lines = []
        self.words = []
        self.string = ''
        self.count_lines = 0
        self.count_words = 0
        self.words_freq = {}
        self.words_per_line = {}
        
        # read files
        with open(self.path) as file:
            self.contents = file.read()
        with open(self.path) as file:
            self.lines = file.readlines()
            for i in range(len(self.lines)):
                self.lines[i] = self.lines[i].replace('\n', '')
                self.lines[i] = self.lines[i].strip()
            while '' in self.lines:
                self.lines.remove('')
        
        # string
        self.string = self.lines[0]
        for line in self.lines[1::]:
            self.string += f" {line}"
        self.string = self.string.lower()
        self.words = self.string.split()
        
        # words per line
        for i in range(len(self.lines)):
            words_line = self.lines[i].split()
            keys = i+1
            self.words_per_line[keys] = len(words_line)
            
    def count_line(self):
            self.count_lines = len(self.lines)
            return self.count_lines
            
    def count_word(self, start_line = None, end_line = None):
        if start_line == None:
            start_line = 1
        if end_line == None:
            end_line = len(self.lines)
        sum_words = sum(self.words_per_line[i] for i in range(start_line, end_line+1))
        return sum_words

    def count_word_freq(self, word_find = None):
        words_set = set(self.words)
        for word in words_set:
            self.words_freq[word] = self.words.count(word)
        if word_find == None:
            return self.words_freq
        else:
            word_find = word_find.lower()
            return self.words_freq[word_find]

### Ex1 - a

In [39]:
story = Story(r'../data/Book/English/shakespeare/Hamlet.txt')
result = {'Hamlet.txt': {}, 'La capitaine.txt': {}}

# a-1
print("Number of words:", story.count_word())
result['Hamlet.txt']["Number of words"] = story.count_word()

# a-2
print("Number of lines:", story.count_line())
result['Hamlet.txt']["Number of lines"] = story.count_line()

# a-3
hamlet_freq = story.count_word_freq("Hamlet")
print('Number of the word "Hamlet":', story.count_word_freq("Hamlet"))
result['Hamlet.txt']['Number of the word "Hamlet"'] = [story.count_word_freq("Hamlet")]
most_freq_word = max(story.words_freq.values())
if hamlet_freq == most_freq_word:
    print(">>> Hamlet is the most frequent word.")
    result['Hamlet.txt']['Number of the word "Hamlet"'].append("the most frequent")
else:
    print(">>> Hamlet is not the most frequent word.")
    result['Hamlet.txt']['Number of the word "Hamlet"'].append("not the most frequent word")

Number of words: 29575
Number of lines: 3966
Number of the word "Hamlet": 100
>>> Hamlet is not the most frequent word.


### Ex1 - b

In [40]:
story2 = Story('../data/Book/French/chevalier/La capitaine.txt')

# b-1
print(">>> Number of words are there from line 100 to line 300:", story2.count_word(start_line = 100, end_line = 300))
result['La capitaine.txt']["Number of words are there from line 100 to line 300"] = story2.count_word(start_line = 100, end_line = 300)

# b-2
words_max_line = max(story2.words_per_line.values())
line_max_words = []
for i in story2.words_per_line:
    if words_max_line == story2.words_per_line[i]:
        line_max_words.append(f'Line {i}')
print("\n>>> Line with the most number of words:", line_max_words)
result['La capitaine.txt']["Line with the most number of words"] = line_max_words

# b-3
words_min_line = min(story2.words_per_line.values())
line_min_words = []
for i in story2.words_per_line:
    if words_min_line == story2.words_per_line[i]:
        line_min_words.append(f'Line {i}')
print("\n>>> Line with the least number of words:", line_min_words)
result['La capitaine.txt']["Line with the least number of words"] = line_min_words

# b-4
line_longest = []
max_length = max(len(i) for i in story2.lines)
for i in range(len(story2.lines)):
    if len(story2.lines[i]) == max_length:
        line_longest.append(f'Line {i+1}')
print("\n>>> Line with the maximum length:", line_longest)
result['La capitaine.txt']["Line with the maximum length"] = line_longest

>>> Number of words are there from line 100 to line 300: 1886

>>> Line with the most number of words: ['Line 3711']

>>> Line with the least number of words: ['Line 13', 'Line 28', 'Line 55', 'Line 72', 'Line 95', 'Line 176', 'Line 191', 'Line 206', 'Line 216', 'Line 244', 'Line 263', 'Line 278', 'Line 293', 'Line 302', 'Line 305', 'Line 311', 'Line 320', 'Line 324', 'Line 332', 'Line 371', 'Line 384', 'Line 445', 'Line 456', 'Line 459', 'Line 500', 'Line 515', 'Line 553', 'Line 559', 'Line 561', 'Line 592', 'Line 596', 'Line 614', 'Line 688', 'Line 758', 'Line 800', 'Line 805', 'Line 827', 'Line 832', 'Line 850', 'Line 854', 'Line 866', 'Line 869', 'Line 885', 'Line 887', 'Line 905', 'Line 909', 'Line 967', 'Line 973', 'Line 977', 'Line 983', 'Line 987', 'Line 1002', 'Line 1009', 'Line 1040', 'Line 1063', 'Line 1073', 'Line 1081', 'Line 1096', 'Line 1104', 'Line 1140', 'Line 1165', 'Line 1195', 'Line 1200', 'Line 1203', 'Line 1212', 'Line 1227', 'Line 1238', 'Line 1246', 'Line 1261',

### Ex1 - c

In [41]:
with open('../output/hw14_result_ex1.json', 'w') as file:
    json.dump(result, file)

## Exercise 2
### Ex2 - 1

In [42]:
a1 = np.zeros(10, dtype = int)
a2 = np.ones(10, dtype = int)
a3 = np.full(10, 5)

### Ex2 - 2

In [43]:
a4 = np.arange(30, 70, 2)
print(a4)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


### Ex2 - 3

In [44]:
a5 = np.eye(3, dtype = int)
print(a5)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Ex2 - 4

In [45]:
a6 = np.random.random()
print(a6)

0.8495434761489726


### Ex2 - 5

In [46]:
a7 = np.random.normal(0, 1, 15)
print(a7)

[-0.39841413 -0.60152791  0.68229428 -0.51467768 -0.32483057 -1.29203047
  0.69592452 -0.50275962  0.7969123   1.01904916 -1.03748773  1.68668815
  0.64887646  0.365577   -1.83057818]


### Ex2 - 6

In [47]:
a8 = np.arange(21)
a8[(a8 >= 9) & (a8 <= 15)] *= -1
print(a8)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


### Ex2 - 7

In [48]:
a9 = np.arange(10, 22).reshape(3,4)
print(a9)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


### Ex2 - 8

In [49]:
a10 = np.zeros((5,5), int)
for i in range(len(a10)):
    for j in range(len(a10[i])):
        if i == j:
            a10[i][j] = i+1
print(a10)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Ex2 - 9

In [50]:
a11 = np.zeros((4,4), int)
for i in range(len(a11)):
    for j in range(len(a11[i])):
        if (i+j)%2 == 1:
            a11[i][j] = 1
print(a11)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


### Ex2 - 10

In [51]:
a12 = np.random.random(10)
print(a12)
a12[a12.argmax()] = 0
print(a12)

[0.33987871 0.83720168 0.40072488 0.87242595 0.82152272 0.55897622
 0.49974107 0.25749621 0.89886    0.49238304]
[0.33987871 0.83720168 0.40072488 0.87242595 0.82152272 0.55897622
 0.49974107 0.25749621 0.         0.49238304]


## Exercise 3

In [52]:
class Matrix:
    
    def __init__(self, matrix):
        self.matrix = matrix
        
    def __repr__(self):
        return str(self.matrix)
    
    def sum_aij_even(self):
        addition_aij_even = 0
        for i in range(len(self.matrix)):
            for j in range(len(self.matrix[i])):
                if (i+j)%2 == 1:
                    addition_aij_even += self.matrix[i][j]
        return addition_aij_even
    
    def transpose_matrix(self):
        index_type = type(self.matrix[0][0])
        shape_t = list(np.shape(self.matrix))
        shape_t = tuple([shape_t[i] for i in range(-1,1)])
        matrix_t = np.zeros(shape_t, index_type)
        for i in range(len(self.matrix)):
            for j in range(len(self.matrix[i])):
                matrix_t[j][i] = self.matrix[i][j]
        return matrix_t
    
    def symmetric_check(self):
        shape = list(np.shape(self.matrix))
        if shape[0] == shape[1]:
            matrix_t = self.transpose_matrix()
            if len(matrix_t[matrix_t != self.matrix]) == 0:
                return True
            else:
                return False
        else:
            return False
    
    def reduce_size_kxk(self):
        index_type = type(self.matrix[0][0])
        shape = list(np.shape(self.matrix))
        if shape[0] > shape[1]:
            row_col = shape[1]
        else:
            row_col = shape[0]
        new_matrix = np.zeros((row_col, row_col), index_type)
        for i in range(row_col):
            for j in range(row_col):
                new_matrix[i][j] = self.matrix[i][j]
        return new_matrix

### Ex3 - a

In [53]:
A = Matrix(np.arange(12).reshape(3,4))
print(A)
sum_aij = A.sum_aij_even()
print("\nSum aij of the matrix A if i+j is even:", sum_aij)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Sum aij of the matrix A if i+j is even: 34


### Ex3 - b

In [54]:
print("A is symmetric?", A.symmetric_check())

B = Matrix(np.array([[1, 2], [2, 1]]))
print("B is symmetric?", B.symmetric_check())

C = B = Matrix(np.array([[1, 2], [3, 1]]))
print("C is symmetric?", C.symmetric_check())

A is symmetric? False
B is symmetric? True
C is symmetric? False


### Ex3 - c

In [55]:
A_kxk = A.reduce_size_kxk()
print(">>> A (k x k):\n", A_kxk)

D = Matrix(np.arange(10).reshape(2,5))
print("\n>>> D:\n", D)
D_kxk = D.reduce_size_kxk()
print("\n>>> D (k x k):\n", D_kxk)

>>> A (k x k):
 [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]

>>> D:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

>>> D (k x k):
 [[0 1]
 [5 6]]


### Ex3 - d

In [56]:
class MatrixUpdate(Matrix):
    def gauss(self):
        array = self.matrix

        # create a copy and convert dtype into float
        matrix = array.copy().astype(float)
        
        row = 0
        while row < matrix.shape[0]:
            row_below = row + 1
            
            col = row
            while matrix[row, col] == 0:
                if row == matrix.shape[0]-1:
                    break
                elif row_below >= matrix.shape[0]:
                    if col < matrix.shape[0]-1:
                        col += 1
                    else:
                        row += 1
                    row_below = row + 1
                else:
                    if matrix[row_below, col] != 0:
                        temp = matrix[row].copy()
                        matrix[row] = matrix[row_below].copy()
                        matrix[row_below] = temp.copy()
                        break
                    else:
                        row_below += 1
            
            if matrix[row, col] != 0:
                matrix[row] = matrix[row]/matrix[row, col]
                for i in range(row+1, matrix.shape[0]):
                    matrix[i] = matrix[i] - matrix[row]*(matrix[i, col]/matrix[row, col])
            
            row += 1
            
        return matrix        
    
    def gauss_jordan(self):
        matrix = self.gauss()
        pivot = []
        col = 0
        row = 0
        while col <= matrix.shape[1]-1:
            if matrix[row, col] != 0:
                pivot.append(col)
                row += 1
            col += 1
        while pivot:
            row = len(pivot)-1
            col = pivot.pop()
            for row_above in range(row-1, -1, -1):
                matrix[row_above] = matrix[row_above] - matrix[row]*(matrix[row_above, col]/matrix[row, col])
        return matrix    

In [57]:
A = MatrixUpdate(np.arange(12).reshape(3,4))
print("Original Matrix:")
print(A)

A = MatrixUpdate(np.arange(12).reshape(3,4))
print("\nGauss Elimination:")
print(A.gauss())

A = MatrixUpdate(np.arange(12).reshape(3,4))
print("\nGauss-Jordan Elimination:")
print(A.gauss_jordan())

Original Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Gauss Elimination:
[[1.   1.25 1.5  1.75]
 [0.   1.   2.   3.  ]
 [0.   0.   0.   0.  ]]

Gauss-Jordan Elimination:
[[ 1.  0. -1. -2.]
 [ 0.  1.  2.  3.]
 [ 0.  0.  0.  0.]]
