__FINAL EXAM__
<br>
Full Name: Nguyễn Thị Minh Ngọc
<br>
Student ID: 11219280
<br>
Class: DSEB 63

In [1]:
import numpy as np
import random
import re
import json
test_no = 6304

# Question 1

In [2]:
stories = ['alice.txt', 'little_women.txt', 'moby_dick.txt', 'siddhartha.txt']
np.random.seed(test_no)
story = random.choice(stories)
print(story)

little_women.txt


In [3]:
class Story:
    def __init__(self, story_name):
        path = f'Data/Stories/{story_name}'
        self.story, self.lines = self.read(path)
        self.storystd, self.linestd = self.standardized()
        
    def read(self, path):
        with open(path) as file:
            story = file.read()
        with open(path) as file:
            lines = file.readlines()
        lines[0] = lines[0][3::]
        return story[3::], lines
    
    def standardized(self):
        storystd = self.story
        linestd = self.lines
        
        # story standardized
        while '\n' in storystd:
            storystd = storystd.replace('\n', ' ')
        storystd = re.sub('[^a-zA-Z0-9 ]', '', storystd)
        while '  ' in storystd:
            storystd = storystd.replace('  ', ' ')
        storystd = storystd.strip()
        storystd = storystd.lower()
        
        # lines standardized
        for i in range(len(linestd)):
            while '\n' in linestd[i]:
                linestd[i] = linestd[i].replace('\n', ' ')
            while '  ' in linestd[i]:
                linestd[i] = linestd[i].replace('  ', ' ')
            linestd[i] = linestd[i].strip()
        while '' in  linestd:
            linestd.remove('')
        return storystd, linestd

    def freq_word_3(self):
        freq_word_3 = {}
        wordlist = self.storystd.split(' ')
        wordset = set(wordlist)
        wordset_3 = []
        for word in wordset:
            if len(word) < 4:
                wordset_3.append(word)
        for word in wordset_3:
            freq_word_3[word] = wordlist.count(word)
        return freq_word_3
    
    def find_word_from_set(self):
        letters = {'s', 't', 'r', 'o', 'n', 'a', 'e', 'h'}
        wordlist = self.storystd.split(' ')
        wordset = set(wordlist)
        words_found = []
        for word in wordset:
            word_letter = word.replace('', '-')
            word_letter = word_letter[1:-1:]
            word_letter = word_letter.split('-')
            count = 0
            for i in word_letter:
                if i in letters:
                    count += 1
            if count == len(word):
                words_found.append(word)
        return set(words_found)

### 1 - a

In [4]:
str1 = Story(story)
print(str1.linestd[-5:len(str1.linestd)])

['http://www.gutenberg.net', 'This Web site includes information about Project Gutenberg-tm,', 'including how to make donations to the Project Gutenberg Literary', 'Archive Foundation, how to help produce our new eBooks, and how to', 'subscribe to our email newsletter to hear about new eBooks.']


### 1 - b

In [5]:
print(str1.freq_word_3())

{'ach': 2, '100': 1, 'opy': 1, 'his': 1116, 'nge': 1, '1f4': 1, 'dis': 1, 'du': 2, 'f3': 1, 'day': 238, 'web': 7, 'do': 707, 'nun': 1, 'eye': 34, 'fog': 3, 'lee': 1, 'bit': 48, 'rap': 3, 'or': 511, 'few': 79, 'hid': 14, 'mud': 10, 'pc': 4, 'lor': 1, 'mit': 1, 'cut': 25, 'dim': 7, 'das': 4, 'yer': 3, 'ed': 1, 'fix': 2, 'age': 18, 'nut': 1, 'gay': 28, 'arm': 51, 'get': 239, 'sp': 1, 'off': 173, '30': 1, 'des': 1, 'gem': 2, 'job': 2, 'coo': 2, 'hot': 23, 'yes': 143, 'ned': 23, 'by': 562, 'gad': 1, 'up': 639, 'gut': 2, 'tag': 1, 'say': 275, 'bob': 2, 'ob': 2, 'fun': 69, '90': 2, 'tt': 1, 'bun': 1, 'ma': 3, 'mes': 3, 'mix': 1, 'pm': 1, 'to': 5148, '1e4': 1, 'pin': 5, '1f2': 1, '1e': 2, 'sit': 38, 'go': 390, '1e3': 1, 'are': 506, 'see': 358, 'ode': 1, '1e6': 1, 'jes': 1, 'too': 197, 'bed': 50, '5': 1, 'wig': 3, 'toe': 1, 'add': 9, 'out': 479, 'iss': 2, 'nip': 1, 'saw': 142, 'po': 2, 'if': 916, 'a': 4509, 'her': 3245, 'am': 123, 'meg': 633, 'eer': 1, 'foe': 1, 'pie': 2, 'my': 843, 'lot': 6, '

# 1 - c

In [6]:
print(str1.find_word_from_set())

{'tt', 'ate', 'serene', 'an', 'tar', 'oar', 'nonsense', 'then', 'senna', 'estates', 'neatness', 'hears', 'roast', 'hen', 'threatens', 'rear', 'as', 'rent', 'enters', 'rats', 'sheet', 'hearten', 'toe', 'she', 'threes', 'heart', 'oer', 'sant', 'arent', 'ashes', 'theaters', 'har', 'reason', 'thethe', 'toss', 'hero', 'set', 'soreness', 'ear', 'honest', 'host', 'other', 'seashore', 'hose', 'shes', 'trot', 'heroes', 'tears', 'hash', 'stare', 'neat', 'heartens', 'note', 'harshness', 'earthe', 'root', 'sons', 'en', 'estate', 'assert', 'resent', 'ran', 'rashness', 'ohs', 'tents', 'theresa', 'atone', 'trees', 'nest', 'nor', 'stares', 'noter', 'hasnt', 'ten', 'soar', 'ease', 'threaten', 'tares', 'sat', 'three', 'short', 'honor', 'err', 'orno', 'torn', 'hannahs', 'star', 'hortense', 'onethe', 'horrors', 'errors', 'soon', 'a', 'hens', 'seats', 'hart', 'error', 'seat', 'shorter', 'teteatete', 'heres', 'earnest', 'ho', 'than', 'sartor', 'earnestness', 'tart', 'rehearse', 'norton', 'soonest', 'tearose

# Question 2

In [7]:
class Matrix:
    def __init__(self, matrix):
        self.matrix = matrix
    
    def __repr__(self):
        return str(self.matrix)
    
    def count_entries_greater_than_6(self):
        return len(self.matrix[self.matrix>6])
    
    def mean_col(self):
        mean_col_result = {}
        matrix_t = np.transpose(self.matrix)
        for i in range(len(matrix_t)):
            mean_col_result[f'Column {i+1}'] = matrix_t[i].mean()
        return mean_col_result
    
    def mean_matrix(self):
        return self.matrix.mean()
    
    def check_prime(self, number):
        if number < 2:
            return False
        else:
            count = 0
            for i in range(1, number+1):
                if number%i == 0:
                    count += 1
            if count == 2:
                return True
            else:
                return False
    
    def check_prime_product(self, number):
        check = False
        for i in range(1, number):
            i2 = int(number/i)
            if i2*i == number:
                if self.check_prime(i) == True and self.check_prime(i2) == True:
                    check = True
        return check
    
    def check_entries_prime_product(self):
        count = 0
        for row in range(self.matrix.shape[0]):
            for col in range(self.matrix.shape[1]):
                if self.check_prime_product(self.matrix[row][col]) == True:
                    count += 1
        return count

In [8]:
np.random.seed(test_no)
A = np.random.randint(0, 16, size = 63).reshape(9,7)
A

array([[ 2,  5, 10, 11,  7,  5,  7],
       [ 6,  2,  3,  7,  8,  8,  1],
       [ 9, 14, 10, 14,  5,  0,  9],
       [ 2, 13, 13, 15,  0,  5, 15],
       [12,  6, 12,  2,  4,  3,  9],
       [ 1,  3, 12,  9, 10,  0,  8],
       [11, 14, 10, 11, 14,  1,  8],
       [12, 11,  0,  9, 13, 14, 10],
       [ 3, 10, 15,  6, 13,  3, 12]])

In [9]:
mtA = Matrix(A)

In [10]:
print('(a) Entries greater than 6:', mtA.count_entries_greater_than_6())
print('\n(b) Mean:\n>>> Mean of the columns of the matrix:', mtA.mean_col())
print('>>> Mean of the matrix:', mtA.mean_matrix())
print('(c) Entries that are product of two prime numbers:', mtA.check_entries_prime_product())

(a) Entries greater than 6: 39

(b) Mean:
>>> Mean of the columns of the matrix: {'Column 1': 6.444444444444445, 'Column 2': 8.666666666666666, 'Column 3': 9.444444444444445, 'Column 4': 9.333333333333334, 'Column 5': 8.222222222222221, 'Column 6': 4.333333333333333, 'Column 7': 8.777777777777779}
>>> Mean of the matrix: 7.888888888888889
(c) Entries that are product of two prime numbers: 23


# Question 3

### 3 - a

In [11]:
def convert_grade_4(point10):
    point4 = (point10/10)*4
    return point4

### 3 - b

In [12]:
filename = 'grade10.json'
with open(f'Data/{filename}') as file:
    grade10 = json.load(file)
print(grade10)

{'An': [9, 9, 5, 7, 5], 'Mai': [10, 9, 6, 5, 7], 'Duong': [5, 6, 4, 7, 7], 'Huy': [8, 4, 6, 8, 5], 'Dung': [7, 8, 10, 4, 10], 'Tam': [10, 6, 5, 8, 4], 'Anh': [5, 10, 5, 8, 8]}


In [13]:
def convert_grade_letter(point4):
    if point4 < 2:
        letter = 'D'
    elif point4 < 2.4:
        letter = 'C'
    elif point4 < 2.8:
        letter = 'B'
    elif point4 < 3.2:
        letter = 'B+'
    elif point4 < 3.6:
        letter = 'A'
    else:
        letter = 'A+'
    return letter

grade_4 = {}
grade_letter = {}
for name in grade10:
    grade_4[name] = []
    for i in grade10[name]:
        grade_4[name].append(convert_grade_4(i))
    grade_letter[name] = []
    for i in grade_4[name]:
        grade_letter[name].append(convert_grade_letter(i))

### 3 - c

In [14]:
newfile = 'grade4.json'
with open(newfile, 'w') as file:
    json.dump(grade_4, file)
    json.dump(grade_letter, file)

# Question 4

In [15]:
np.random.seed(test_no)
C = np.random.randint(1, 5, 36).reshape(6, 6)
C = C + C.T
C = C - np.diag(C.diagonal())
print(C)

[[0 6 4 6 8 3]
 [6 0 5 5 5 4]
 [4 5 0 5 5 4]
 [6 5 5 0 6 6]
 [8 5 5 6 0 5]
 [3 4 4 6 5 0]]
